# Generated by Django 4.1.7 on 2023-02-23 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200, null=True, unique=True)),
                ('hostname', models.CharField(max_length=200, null=True)),
                ('port', models.IntegerField()),
                ('platform', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('groups', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=200, null=True)),
                ('host_snmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snmpFilter.information', to_field='host')),
            ],
        ),
    ]
