# Generated by Django 4.1.7 on 2023-02-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmpFilter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snmp',
            old_name='oid',
            new_name='community',
        ),
    ]
